name: "GHA - FE LIB APP knip"
run-name: "Knip Frontend Lib App"
on: [pull_request, workflow_dispatch]

jobs:
  frontendLibAppKnip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Volta
        run: |
          curl https://get.volta.sh | bash
          echo "$HOME/.volta/bin" >> $GITHUB_PATH

      - name: Install packages
        run: |
          volta install node yarn
          yarn install --frozen-lockfile
        working-directory: ./src-frontend-app-web

      - name: Run knip
        run: yarn gha:knip
        working-directory: ./src-frontend-app-web
